// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"rpc/userrpc/internal/logic"
	"rpc/userrpc/internal/svc"
	"rpc/userrpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetName(ctx context.Context, in *user.IdRequest) (*user.NameResponse, error) {
	l := logic.NewGetNameLogic(ctx, s.svcCtx)
	return l.GetName(in)
}
