// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type RegisterReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResp struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	Need2FA        bool   `json:"need2fa"`
	ChallengeToken string `json:"challengeToken,omitempty"`
	AccessToken    string `json:"accessToken,omitempty"`
	AccessExpire   int64  `json:"accessExpire,omitempty"`
}

type EmptyReq struct{}

type TotpEnrollStartResp struct {
	Issuer        string `json:"issuer"`
	AccountName   string `json:"accountName"`
	OTPAuthURL    string `json:"otpauthUrl"`
	QRCodeDataURL string `json:"qrCodeDataUrl"`
}

type TotpCodeReq struct {
	Code string `json:"code"`
}

type TotpToggleResp struct {
	Enabled bool `json:"enabled"`
}

type TotpVerifyReq struct {
	ChallengeToken string `json:"challengeToken"`
	Code           string `json:"code"`
}

type TotpVerifyResp struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type Disable2FAReq struct {
	Password string `json:"password"`
	Code     string `json:"code"`
}
