// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type HelloReq struct {
	Name string `path:"name"`
}

type HelloResp struct {
	Message string `json:"message"`
}

type SummaryReq struct {
	Name string `form:"name,optional"`
	Uid  string `form:"uid,optional"`
	Vid  string `form:"vid,optional"`
}

type SummaryResp struct {
	Greeting string `json:"greeting"`
	UserName string `json:"userName"`
	Title    string `json:"title"`
}

type UserNameReq struct {
	Id string `path:"id"`
}

type UserNameResp struct {
	Name string `json:"name"`
}

type VideoTitleReq struct {
	Id string `path:"id"`
}

type VideoTitleResp struct {
	Title string `json:"title"`
}
