// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"totp/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/generate",
				Handler: generateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/verify",
				Handler: verifyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/qrcode",
				Handler: qrcodePNGGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/qrcode",
				Handler: qrcodePNGPostHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/totp"),
	)
}
