// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type UploadResp struct {
	Filename string `json:"filename"`
	Size     int64  `json:"size"`
	URL      string `json:"url"`
}

type GetFileReq struct {
	FileURL string `path:"filename"`
}
