// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	demo "rpc/gateway/internal/handler/demo"
	"rpc/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/hello/:name",
				Handler: demo.HelloHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/summary",
				Handler: demo.SummaryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/name/:id",
				Handler: demo.UserNameHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/video/title/:id",
				Handler: demo.VideoTitleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
