// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"mysql/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: registerHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: loginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/2fa/totp/enroll/start",
				Handler: totpEnrollStartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/2fa/totp/enroll/confirm",
				Handler: totpEnrollConfirmHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/2fa/verify",
				Handler: totpVerifyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/2fa/totp/disable",
				Handler: totpDisableHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/users"),
	)
}
