// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"demo01/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user/class/add",
				Handler: UserClassAddHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/class/delete",
				Handler: UserClassDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/class/info",
				Handler: UserClassInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/class/list",
				Handler: UserClassListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/class/update",
				Handler: UserClassUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/info",
				Handler: UserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/info/update",
				Handler: UserInfoUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/list",
				Handler: UserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: UserLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/role/add",
				Handler: UserRoleAddHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/role/delete",
				Handler: UserRoleDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/role/info",
				Handler: UserRoleInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/role/list",
				Handler: UserRoleListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/role/update",
				Handler: UserRoleUpdateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
