// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: video.proto

package videoclient

import (
	"context"

	"rpc/videorpc/video"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IdRequest     = video.IdRequest
	TitleResponse = video.TitleResponse

	Video interface {
		GetTitle(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*TitleResponse, error)
	}

	defaultVideo struct {
		cli zrpc.Client
	}
)

func NewVideo(cli zrpc.Client) Video {
	return &defaultVideo{
		cli: cli,
	}
}

func (m *defaultVideo) GetTitle(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*TitleResponse, error) {
	client := video.NewVideoClient(m.cli.Conn())
	return client.GetTitle(ctx, in, opts...)
}
