// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package userclient

import (
	"context"

	"rpc/userrpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IdRequest    = user.IdRequest
	NameResponse = user.NameResponse

	User interface {
		GetName(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*NameResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetName(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*NameResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetName(ctx, in, opts...)
}
