// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: video.proto

package server

import (
	"context"

	"rpc/videorpc/internal/logic"
	"rpc/videorpc/internal/svc"
	"rpc/videorpc/video"
)

type VideoServer struct {
	svcCtx *svc.ServiceContext
	video.UnimplementedVideoServer
}

func NewVideoServer(svcCtx *svc.ServiceContext) *VideoServer {
	return &VideoServer{
		svcCtx: svcCtx,
	}
}

func (s *VideoServer) GetTitle(ctx context.Context, in *video.IdRequest) (*video.TitleResponse, error) {
	l := logic.NewGetTitleLogic(ctx, s.svcCtx)
	return l.GetTitle(in)
}
