// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type GenerateReq struct {
	AccountName string `json:"accountName"`
	Issuer      string `json:"issuer,omitempty"`
}

type GenerateResp struct {
	Secret      string `json:"secret"`
	Issuer      string `json:"issuer"`
	AccountName string `json:"accountName"`
	OTPAuthURL  string `json:"otpauthUrl"`
}

type VerifyReq struct {
	Secret string `json:"secret"`
	Code   string `json:"code"`
}

type VerifyResp struct {
	Valid bool `json:"valid"`
}

// QRCodeReq 用于 POST /api/totp/qrcode，返回 PNG 图片（非 JSON）。
type QRCodeReq struct {
	OTPAuthURL string `json:"otpauthUrl"`
}
