// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

import "time"

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken  string    `json:"token"`
	RefreshToken string    `json:"refresh_token"`
	ExpiresIn    time.Time `json:"expriesin"`
}

type ProfileReq struct {
	TargetId int64 `json:"targe_id"`
}

type LogoutReq struct {
	TargetId int64 `json:"targe_id"`
}

type ProfileResp struct {
	UserID    int64  `json:"user_id"`
	Username  string `json:"username"`
	Email     string `json:"email"`
	CreatedAt string `json:"created_at"`
}

type RefreshReq struct {
	RefreshToken string `json:"refresh_token"`
}
